# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

platform :ios do

  before_all do |lane, options|
     detect_environment_information
    
     after_all do |lane, options|

     end

     error do |lane, exception|
       UI.error("Error block excecuting...")
       UI.error("|Error block| lane = " + lane.to_s)
       UI.error("|Error block| exception = " + exception.to_s)
     end
     
  end

 lane :printMessageLane do
       UI.message("Ready to execute fastlane script testing is done")
  end

 lane :readMessagLane do
       UI.message("Reading Message from Envioroment which present on Source directory: " + Actions.lane_context[SharedValues::GENRIC_MESSAGE].to_s)
  end

 lane :buildiOSSource do
      build_source_code
  end

 lane :testiOSSource do
      test_source_code
  end

 lane :podLibLint do
      pod_lib_lint
  end

  lane :publishNewPodSpec do
      publish_pod
  end

  lane :publishSPM do
      publish_s_p_m
  end

end


